spring:
    application:
        name:queryExecution
    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    data:
        mongodb:
            uri: "mongodb://localhost:3000/db"
            sub_query_collection_name: "${subQueryCollection:sub_queries}"
single_index_searcher_count: ${INDEX_FILES_COUNT:64}
cloudwatch_namespace: ${CLOUDWATCH_NAMESPACE:DQS}
output_folder_path: ${OUTPUT_FOLDER_PATH:https://test-bucket.s3.us-east-1.amazonaws.com/result}
tenant_ids: ${tenants:jpmc}