apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "dqs-query-execution-%s-service-account" .Values.TENANTS}}
  namespace: {{ printf "%s-%s" .Values.namespace .Values.TENANTS }}
  annotations:
    eks.amazonaws.com/role-arn: {{  .Values.MSK_ROLE_ARN }}
