{{- range .Values.TENANTS }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "dqs-query-execution-%s-service-account" .}}
  namespace: {{ printf "%s-%s" $.Values.namespace . }}
  annotations:
    eks.amazonaws.com/role-arn: {{  $.Values.MSK_ROLE_ARN }}
---
{{- end }}
