apiVersion: v1
kind: ServiceAccount
metadata:
  name: dqs-query-execution-service-account
  namespace: {{ printf "%s-%s" .Values.namespace .Values.TENANTS }}
  annotations:
    eks.amazonaws.com/role-arn: {{  .Values.MSK_ROLE_ARN }}
